services:
  - type: web
    name: restaurant-management-system
    env: node
    buildCommand: cd restaurant-mgmt && npm install && npm run build
    startCommand: cd restaurant-mgmt && npm run start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000 