services:
  - type: web
    name: restaurant-management-system
    env: node
    buildCommand: cd restaurant-mgmt && npm install && npm run build
    startCommand: cd restaurant-mgmt && npm install && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18 